### ISSUE TITLE
Note VC runtime dependency

### ISSUE THREAD

**Issue by jzebedee** [TimMisiak/windup#1]
Please document the requirement for installing the appropriate [Visual C++ Redistributable Runtime](https://www.microsoft.com/en-us/Download/confirmation.aspx?id=48145).

If this runtime is not present, opening Windup will fail with this error:
![Screenshot 2023-07-10 104148](https://github.com/TimMisiak/windup/assets/1896945/d1be6e22-fb89-4c81-8b1c-0a25f4ce7769)

This can be reproduced from any Windows Sandbox or fresh VM environment.

**Comment by TimMisiak** [comment]
Thanks, I didn't even realize the default rust compilation was linking to that. I think I can switch it to statically link.
